### ISSUE TITLE
Gedoe met not serializable na toevoegen Callback in chat java app

### ISSUE THREAD

**Issue by bartvanderwal** [bartvanderwal/java-rmi#3]
Hieronder de error. Deze StackOverflow lijkt over hetzelde te gaan, maar fix lost error nog niet op:
https://stackoverflow.com/questions/11049810/rmi-notserializableexception-although-its-a-remote-object#11050127

```console
@bartvanderwal ➜ /workspaces/java-rmi (callback) $ ./run-client 
Client logger aangemaakt. LogLevel is: INFO
Ok, host: 'localhost'.
Chat Client: chatCallback registreren bij registry.
Chat client gestart.
Exception in thread "main" chatjava.ChatJavaException: Client aanmaak error. Message: error marshalling arguments; nested exception is: 
        java.io.NotSerializableException: chatjava.rmi.HalloRmiClient$$Lambda$64/0x000000010010e840
        at chatjava.ChatClientApp.main(ChatClientApp.java:32)
Caused by: java.rmi.MarshalException: error marshalling arguments; nested exception is: 
        java.io.NotSerializableException: chatjava.rmi.HalloRmiClient$$Lambda$64/0x000000010010e840
        at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:160)
        at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
        at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:162)
        at com.sun.proxy.$Proxy2.zegHallo(Unknown Source)
        at chatjava.rmi.HalloRmiClient.startDialoog(HalloRmiClient.java:62)
        at chatjava.ChatClientApp.main(ChatClientApp.java:30)
Caused by: java.io.NotSerializableException: chatjava.rmi.HalloRmiClient$$Lambda$64/0x000000010010e840
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
        at java.rmi/sun.rmi.server.UnicastRef.marshalValue(UnicastRef.java:293)
        at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:155)
        ... 5 more
```

**Comment by bartvanderwal** [comment]
Ah, de error was dat ik van de callback de lambda meegaf in de functie, zoals ik gewend ben in JavaScript, maar voor RMI moet je een object (instantie van ClientCallbackInterface) meegeven, en in ontvanger op dit object de methode aanroepen.

Een methode heeft namelijk nooit type `Remote`, zoals de SO post aangeeft dat het moet zijn (e.g. een 'Exported remote) (maar een methode heeft een 'X -> Y' achtige type, zoals je vastlegt in de functional interface in Java).
